### ISSUE TITLE
feat: add useWorker

### ISSUE THREAD

**Issue by logaretm** [logaretm/vue-use-web#25]
It would be similar to the `useWebsocket` API, as it is only concerned with calling the web worker API and providing wrapping for sending and react to incoming data.

```js
const { message, post, terminate } = useWorker('path/to/worker.js');

watch(message, (value) => {
  console.log('Worker says: ', value);
}, { lazy: true });

// send a message from the main script.
post('hello from main script!');

terminate(); // cleans up the worker
```

**Comment by izhuravlev** [comment]
Hey @logaretm, 
I can work on it

**Comment by logaretm** [comment]
Sure, Go for it!

**Comment by izhuravlev** [comment]
@logaretm Can't clearly understand what message function does - can you please add a little explanation?

**Comment by logaretm** [comment]
Sure, the `message` would be a reference to the last received item from the web worker, you can think of it as the `data` like in the `useWebSocket`  function.

Feel free to rename it, I only suggested the API that's closest to the native terminology.
