### ISSUE TITLE
add usePreferredColorScheme

### ISSUE THREAD

**Issue by logaretm** [logaretm/vue-use-web#6]
This API should track color scheme preference of the user.

Should look like this:

```js
const theme = usePreferredColorScheme();

// theme can be either "dark", "light" or "no-preference".
```

Hint: Check the `window.matchMedia` function.

Don't forget to add docs for it as well!

**Comment by kimuraz** [comment]
@logaretm can I work on this one?

**Comment by logaretm** [comment]
Sure, go right ahead, looking forward to what you will do!
