### ISSUE TITLE
add usePreferredLanguages

### ISSUE THREAD

**Issue by logaretm** [logaretm/vue-use-web#7]
This API should track the language preference of the user.

Should look like this:

```js
const languages = usePreferredLanguages();

// language is an array of language codes, like ['en-US', 'ar']
```

Hint: Check the `navigator` object for useful properties and event listeners.

Don't forget to add docs for it as well!

**Comment by infix** [comment]
I'd like to work on this.

**Comment by logaretm** [comment]
Go ahead, looking forward to what you come up with.
