### ISSUE TITLE
Publish types

### ISSUE THREAD

**Issue by dodas** [logaretm/vue-use-web#9]
Hi, thanks for library! Going to use it for sure.

I just noticed that TypeScript types are perhaps not published in npm package, therefore getting error: `Could not find a declaration file for module 'vue-use-web'.`

Could you make sure to publish `.d.ts` files as well?

Edit: Just running `npm run ts:defs` inside `node_modules/vue-use-web` fixed the error, so you probably just need to include that in your publish workflow.

**Comment by logaretm** [comment]
This is fixed, you can use `0.1.2` now to get the typed version, thanks for reporting this!
